SDKCONFIG-50 adjusted OneginiConfigModel for SCv2 m2
Onegini/onegini-sdk-configurator pull request #33
Opened 2021-03-11 13:46 UTC by lukaszlabunski

2021-03-15 16:29 UTC, stnslw requested changes
- readme is not update with new ios sdk version
- ios sdk docs are not updated

2021-03-16 08:40 UTC, lukaszlabunski commented
> * readme is not update with new ios sdk version

I assume that should be done in scope of release task because the version is not known yet.

2021-03-16 11:35 UTC, lukaszlabunski commented
> * ios sdk docs are not updated

Docs were updated in SCv2 M2 story.

2021-03-17 15:32 UTC, stnslw approved these changes

2021-03-17 15:32 UTC, merged